name: Deploy to Server
on:
  push:
    branches:
      - main

jobs:
  primer_job:
    name: Primer Job
    runs-on: ubuntu-latest

    steps:
      - name: Generar Archivo de Salida
        run: |
           echo "Archivo de Prueba, Hola Lobo" >> text.log
      
      - name: Subir Archivo Generado
        uses: actions/upload-artifact@v4
        with:
          name: archivo-test
          path: text.log       
 