name: Deploy to Server
on:
  push:
    branches:
      - main

jobs:
  primer_job:
    name: Primer Job
    runs-on: ubuntu-latest

    steps:
      - name: Generar Archivo de Salida
        run: |
           echo "Archivo de Prueba, Hola Lobo" >> text.log
      
      - name: Subir Archivo Generado
        uses: actions/upload-artifact@v4
        with:
          name: archivo-test
          path: text.log       
 
  Segundo_job:
    need: primer_job
    name: Segundo Job
    runs-on: ubuntu-latest

    steps:
      - name: Descargamos el artefacto generado
        uses: actions/download-artifact@v4
        with:
          name: archivo-test

      - name: Visualizamos contenido del archivo descargado
        run: |
          cat text.log       
       