name: Deploy to Server
on:
  push:
    branches:
      - main

jobs:
  primer_job:
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run: echo "Hola primer Mundo"

  segundo_job:
    needs: primer_job
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run: echo "Hola segundo Mundo" 